### ISSUE TITLE
Suggestion: add better checks around host-hostess 

### ISSUE THREAD

**Issue by hiimbex** [get-alex/alex#188]
Hello there! My team uses [linter-alex](https://probot.github.io/apps/linter-alex/) to lint PRs, and ran into a this [check](https://github.com/probot/hello-world/pull/5/checks?check_run_id=4591249) which is failing for [this](https://github.com/probot/hello-world/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R29) use of "host". Not a huge deal, but I'd prefer if our checks passed and since this use of host makes sense to me, I'd wondered if there was a fix on your end.

**Comment by wooorm** [comment]
Hi Bex! 👋

Thanks for chiming in. This is not something that can change: alex isn’t very smart in catching things, it has no sense of context, and that’s what is needed to be able to deal with this case.

However, there are several ways to ignore messages. You can ignore `host` in all files by [allowing](https://github.com/wooorm/alex#ignoring-messages), or in this specific case with [disable or ignore](https://github.com/wooorm/alex#control) comments.

And finally, there’s the --diff flag, but that won’t work in the probot package.
It looks like the 🤖 package processed the whole document, instead of just the changed lines?
In fact, I think there’s no support in the 🤖 package to ignore messages? 🤔

Maybe we can collaborate on a package like [`unified-engine-atom`](https://github.com/unifiedjs/unified-engine-atom), which makes it easy to create an Atom linter from a [unified](https://unifiedjs.github.io) processor (such as [`atom-linter-alex`](https://github.com/wooorm/atom-linter-alex)), but for probot apps.

**Comment by wooorm** [comment]
@hiimbex Ping :)

**Comment by hiimbex** [comment]
Hi @wooorm! sorry for the delay. I'm totally in support of all these ideas, but I'm really swamped right now, so I doubt I'll have the bandwidth to work on this anytime in the near future. 

Feel free to close this out if you don't think anyone will be able to work on it anytime soon.

**Comment by wooorm** [comment]
Thanks for getting back to me, Bex!
Well in that case I’ll close it for now, but I’d like to collaborate on it if you’re up for it in the future!
