### ISSUE TITLE
Will Alex support Chinese in the future

### ISSUE THREAD

**Issue by ZsgsDesign** [get-alex/alex#248]
Chinese is one of the most commonly used languages in the world. But it's grammarians and vocabularies are quite a mass. Will Alex support Chinese in the near future?

**Comment by wooorm** [comment]
Chinese is important, yes! As is internationalisation in general, so I’m happy that work is being done in [cuss](https://github.com/words/cuss) to support other languages. We’d also need translations in [retext-equality](https://github.com/retextjs/retext-equality) to actually support non-English here in alex as well, but that’s doable.

The problem with non-Latin-script languages such as Chinese is that alex works on a syntax tree of languages to know what paragraphs, sentences, words, symbols, punctuation, etcetera are (see [parse-latin](https://github.com/wooorm/parse-latin)). To support other scripts, we need other projects like that. And I can’t write them.

Some work has been done for Japanese, but it hasn’t been connected to [retext](https://github.com/retextjs/retext) yet, which also needs to happen.

This is a _lot_ of work which I personally cannot do as I or other maintainers don‘t speak Chinese (but we can help a bit of course). Some people have tried over the last few years but I believe that work has been abandoned.

Because it’s not very actionable, I’ll close this issue, but if you or anyone is willing and able to do the work, we can help!
