### ISSUE TITLE
Upgrade to update-notifier@4.0.0

### ISSUE THREAD

**Issue by jeff-cook** [get-alex/alex#272]
### Vulnerability in sub module

https://app.snyk.io/test/npm/alex/8.1.1

MEDIUM SEVERITY NEW
Prototype Pollution
Vulnerable module: dot-prop
Introduced through: update-notifier@3.0.1
Detailed paths
Introduced through: alex@8.1.1 › update-notifier@3.0.1 › configstore@4.0.0 › dot-prop@4.2.0
Remediation: Upgrade to update-notifier@4.0.0.
Overview
dot-prop is a package to get, set, or delete a property from a nested object using a dot path.

Affected versions of this package are vulnerable to Prototype Pollution. It is possible for a user to modify the prototype of a base object.

**Comment by wooorm** [comment]
Thanks Jeff! While there may be an issue in `dot-prop` in certain cases, it’s unlikely to affect `configstore`, which is extremely unlikely to affect `update-notifier`, which is improbable to affect `alex`. As a maintainer, I appreciate that bots warn me, but they are most often false-positives, as is this case.

I don’t see any reason in updating now, and creating a major release (because an update to update-notifier would mean breaking Node 8): it introduces churn to our users. alex is such a stable project that I’d rather stay on the regular once-a-year major update and not include this update yet.
