### ISSUE TITLE
Renovate

### ISSUE THREAD

**Issue by jeff-cook** [get-alex/alex#273]
### Renovate

Check out https://github.com/marketplace/renovate to keep the dependencies up to date.

### Problem

Dependencies are not keep updated.

### Expected behaviour

Dependencies are not being updated. 

### Alternatives

- https://github.com/marketplace/renovate
- https://github.com/marketplace/dependabot-preview
- https://www.dependencies.io/
- https://github.com/marketplace/snyk

**Comment by wooorm** [comment]
Hey thanks! I know renovate, and its alternatives, however, I feel they provide too much noise. alex is a very stable project, it’s not really vulnerable to security problems because (in fact, I’d wager that updating to new versions proves a higher risk than being stable), and I regularly look after it to see what’s up.

So I’m going to decline on adding bots in this case, thanks though!
