### ISSUE TITLE
"just" flagged as insensitive

### ISSUE THREAD

**Issue by bshaffer** [get-alex/alex#277]
### Subject of the issue

The word "just" is being flagged as insensitive

### Your environment

https://alexjs.com/#content

### Steps to reproduce

Type "just" into the linter

![Screen Shot 2020-06-10 at 11 01 06 AM](https://user-images.githubusercontent.com/103941/84302195-ca946680-ab09-11ea-83bc-59bff0615db0.png)

### What should happen

"just" should not be flagged as insensitive

**Comment by wooorm** [comment]
Hi there, welcome! 👋

This is intentional, see here for the discussion: https://github.com/retextjs/retext-equality/issues/45, and here for the source: https://css-tricks.com/words-avoid-educational-writing/#6-just

Also note that alex points that things *may* be insensitive, use your own and others’ judgement!
